# Generated by Django 5.1.2 on 2024-11-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0008_usuarios_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idlogin',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(blank=True, db_column='Contrasena', max_length=150, null=True),
        ),
    ]
