# Generated by Django 5.1.2 on 2024-11-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0010_usuarios_ultimoacceso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidas',
            options={'managed': True},
        ),
    ]
