# Generated by Django 5.1.2 on 2024-11-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0011_alter_medidas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferencias',
            options={'managed': True},
        ),
    ]
