# Generated by Django 5.1.2 on 2024-11-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0012_alter_preferencias_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencias',
            name='calzado',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='pantalon',
        ),
        migrations.AddField(
            model_name='preferencias',
            name='accesorios',
            field=models.CharField(blank=True, db_column='Accesorios', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='cortecabello',
            field=models.CharField(blank=True, db_column='CorteCabello', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='tintecabello',
            field=models.CharField(blank=True, db_column='TinteCabello', max_length=50, null=True),
        ),
    ]
