# Generated by Django 5.1.2 on 2024-11-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0013_remove_medidas_entrepierna_remove_medidas_pecho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='maquillaje',
            field=models.CharField(blank=True, db_column='Maquillaje', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='recomendaciones',
            field=models.CharField(blank=True, db_column='Recomendaciones', max_length=50, null=True),
        ),
    ]
