# Generated by Django 5.1.2 on 2024-11-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0014_remove_medidas_entrepierna_remove_medidas_pecho_and_more'),
    ]

    operations = [
       
    ]
