# Generated by Django 5.1.2 on 2024-11-11 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0016_colorimetria_idusuario_colorimetria_tono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorimetria',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='entrepierna',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='pecho',
        ),
        migrations.AddField(
            model_name='medidas',
            name='hombros',
            field=models.DecimalField(blank=True, db_column='Hombros', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medidas',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estilist_backend.usuarios'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estilist_backend.usuarios'),
        ),
    ]
