# Generated by Django 5.1.2 on 2024-11-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0018_colorimetria_idusuario_alter_colorimetria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorimetria',
            name='tono',
            field=models.CharField(blank=True, db_column='Tono', max_length=50, null=True),
        ),
    ]
