# Generated by Django 5.1.2 on 2024-11-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0019_alter_colorimetria_tono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sesiones',
        ),
    ]
