# Generated by Django 5.1.2 on 2024-11-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0020_delete_sesiones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recomendaciones',
            options={'managed': True},
        ),
    ]
