# Generated by Django 5.1.2 on 2024-11-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0021_alter_recomendaciones_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendaciones',
            name='cont_ranking',
            field=models.SmallIntegerField(blank=True, db_column='Cont_Ranking', null=True),
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='ranking',
            field=models.DecimalField(blank=True, db_column='Ranking', decimal_places=2, max_digits=5, null=True),
        ),
    ]
