# Generated by Django 5.1.2 on 2024-12-01 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0022_recomendaciones_cont_ranking_recomendaciones_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('idstreak', models.AutoField(db_column='IdStreak', primary_key=True, serialize=False)),
                ('ultimasesion', models.DateTimeField(blank=True, db_column='UltimaSesion', null=True)),
                ('dias', models.SmallIntegerField(blank=True, db_column='Dias', null=True)),
                ('idusuario', models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estilist_backend.usuarios')),
            ],
            options={
                'db_table': 'Streak',
                'managed': True,
            },
        ),
    ]
